[package]
name = "dcbor-cli"
version = "0.4.0"
edition = "2021"
description = "Command line parser/validator for deterministic CBOR (\"dCBOR\")."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
license = "BSD-2-Clause-Patent"
repository = "https://github.com/BlockchainCommons/bc-dcbor-cli"
readme = "README.md"
categories = ["data-structures", "encoding"]

[[bin]]
name = "dcbor"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dcbor = "0.13"
clap = { version = "4.0.0", features = ["derive"] }

[dev-dependencies]
indoc = "2.0.0"
